config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  root to: 'poilus#index'
  resources :poilus do
    resources :bookings, only: [ :new, :create, :update, :edit, :destroy]
  end
  get '/poilus/:poilu_id/bookings/:booking_id/pay', to: 'bookings#pay', as: :pay
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/poilu.rb
class Poilu < ApplicationRecord
  LOCATIONS = ['Lausanne','Renens','Genève','Bern','Zürich','Neuchâtel','Fribourg']

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :location, presence: true
  validates :photo, presence: true
  validates :price, presence: true
end

app/controllers/poilus_controller.rb
class PoilusController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_poilu, only: [:show, :edit, :update, :destroy]
  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @poilus = policy_scope(Poilu).where(sql_query, query: "%#{params[:query]}%")
    else
      @poilus = policy_scope(Poilu).order(created_at: :desc)
    end

  end

  def new
    @poilu = Poilu.new
    authorize @poilu
  end

  def create
    @poilu = current_user.poilus.new(poilu_params)
    authorize @poilu
    if @poilu.save
      redirect_to @poilu
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @poilu.update(poilu_params)

    redirect_to poilu_path(@poilu)
  end

  def destroy
    @poilu.destroy
    redirect_to poilus_path
  end

  private

  def set_poilu
    @poilu = Poilu.find(params[:id])
    authorize @poilu
  end

  def poilu_params
    params.require(:poilu).permit(:name, :description, :location, :photo, :price)
  end
end

app/views/poilus/_editform.html.erb
<div class="form-container">
  <h2>Ajouter un poilu</h2>
  <%= simple_form_for(@poilu) do |f| %>
    <% if @poilu.errors.any? %>
      <div class="errors-container">
        <ul>
        <% @poilu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        </ul>
        <% end %>
      </div>
    <% end %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= f.input :name, label: "Nom du poilu"%>
    <%= f.input :description, label: "Description du poilu" %>
    <%= f.input :price, label: "Prix par jour" %>
    <%= f.input :location, collection: Poilu::LOCATIONS, label: "Emplacement du poilu" %>
    <%= f.input :photo, as: :file,label: "Photo du poilu" %>
    <%= f.submit "Editer le poilu", class: "bouton bouton-2" %>
  <% end %>
</div>

app/views/poilus/_form.html.erb
<div class="form-container">
  <h2>Ajouter un poilu</h2>
  <%= simple_form_for(@poilu) do |f| %>
    <% if @poilu.errors.any? %>
      <div class="errors-container">
        <ul>
        <% @poilu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        </ul>
        <% end %>
      </div>
    <% end %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= f.input :name, label: "Nom du poilu"%>
    <%= f.input :description, label: "Description du poilu" %>
    <%= f.input :price, label: "Prix par jour" %>
    <%= f.input :location, collection: Poilu::LOCATIONS, label: "Emplacement du poilu" %>
    <%= f.input :photo, as: :file,label: "Photo du poilu" %>
    <%= f.submit "Ajouter le poilu", class: "bouton bouton-2" %>
  <% end %>
</div>

app/views/poilus/edit.html.erb
<%= render 'editform', poilu: @poilu %>

app/views/poilus/index.html.erb
<div class="banner">
  <div class="container">
    <h1>Trouve ton poilu!</h1>
    <p>Un site vraiment super poilant.</p>
  </div>
</div>

<div class="container">
  <div class="search">
    <%= form_tag poilus_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Trouve ton poilu"
      %>
      <div class="btn-search"><%= submit_tag "Chercher", class: "bouton-2 bouton" %></div>
    <% end %>
  </div>
  <div class="cards">
    <% @poilus.each do |poilu| %>
      <%= link_to poilu_path(poilu) do %>
        <div
          class="card-category"
          style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)),
          <%= poilu.photo.attached? == true ? "url('#{cl_image_path(poilu.photo.key, height: 300, width: 400, crop: :fill)}')" : "url(#{image_path("default.jpg")})" %>"
          >
          <div class="poilu-location">
            <p><i class="fas fa-map-marker-alt"></i><%= poilu.location %></p>
          </div>
          <div class="poilu-name">
            <h3><%= poilu.name %></h3>
            <p>un poilu de <%= image_tag "profile.png", class: "avatar avatar-user" %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/poilus/new.html.erb
<%= render 'form', poilu: @poilu %>

app/views/poilus/show.html.erb
<div class="showcontainer">
<div class="show-img" style="background-image: url(<%= @poilu.photo.attached? ? cl_image_path(@poilu.photo.key) : image_path("default.jpg") %>); background-size: cover;">
      <% if policy(@poilu).destroy? %>
          <p><%= link_to '<i class="fas fa-trash-alt"></i> Supprimer'.html_safe, poilu_path(@poilu), method: :delete, data: { confirm: "Are you sure?" }, class: 'link'  %> </p>
      <% end %>

      <% if policy(@poilu).edit? %>
        <p><%= link_to '<i class="fas fa-edit"></i> Éditer'.html_safe, edit_poilu_path, class: 'link'  %></p>
      <% end %>

  </div>

  <div class="description">

    <h2><%= @poilu.name %></h2>
    <div class="align-location">
      <p><i class="fas fa-map-marker-alt"></i><%= @poilu.location %></p>
      <% if policy(@poilu).edit? %>
        <p>Ce poilu m'appartient</p>
      <% else %>
        <p>Ce poilu appartient à <%= @poilu.user.username %></p>
      <% end %>
    </div>
    <div class="container-description legendes text-medium">
      <h3>À propos de ce Poilu</h3>

      <p><%= @poilu.description %></p>
    </div>
    <p><%= @poilu.price %> CHF/jour</p>
    <div><%= link_to "Je le veux", new_poilu_booking_path(@poilu), class: "bouton bouton-2 boutton-show" %></div>

    <p><%= link_to '<i class="fas fa-chevron-left"></i> Retour'.html_safe, poilus_path, class: 'link back' %></p>
  </div>
</div>