config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  root to: 'poilus#index'
  resources :poilus do
    resources :bookings, only: [ :new, :create, :update, :edit, :destroy]
  end
  get '/poilus/:poilu_id/bookings/:booking_id/pay', to: 'bookings#pay', as: :pay
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :poilus, through: :bookings
  has_many :poilus, dependent: :destroy
  has_one_attached :photo
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    authorize @user
    @poilus = @user.poilus
    @bookings = @user.bookings
  end

end

app/views/users/show.html.erb
<div class="header-profile">
  <h1 >Bonjour <%= @user.username %></h1>
  <p>bienvenue sur ton profil</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="main-box">

        <div class="poilu-boxes">

<!-- ----------MES POILUS----------- -->
          <div class="my-poilus poil-container">
            <h3>Mes poilus</h3>

            <% @user.poilus.each do |poilu| %>
              <div class="poilu-category">

                <div class="poilus-infos">
                  <h4><%= poilu.name %></h4>
                  <p class="added-at"> (ajouté le : <%= poilu.created_at.strftime("%A %d %B, %Y") %>)</p>
                </div>

                <div class="infos purpleBorder">
                  <% if poilu.bookings.size > 0 %>
                    <p class="reserved">Ce poilu est réservé!</p>
                    <% poilu.bookings.each do |booking| %>
                      <p class="small-resa"><i class="fas fa-arrow-right"></i>du <%= booking.start_date.strftime("%A %d %B, %Y") %> au <%= booking.end_date.strftime("%A %d %B, %Y") %> par <%= booking.user.username %></p>
                    <% end %>
                  <% else %>
                    <p class="font-size center-align">Pas de réservations</p>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>

<!-- ----------MES BOOKINGS----------- -->

          <div class="my-bookings poil-container">

            <h3> Mes réservations</h3>
            <% if @bookings.size > 0 %>
              <% @bookings.each do |booking| %>
            <div class="booking-category poilu-category">
              <h4><%= booking.poilu.name %></h4>
              <p><strong>réservé</strong> du <%= booking.start_date.strftime("%A %d %B, %Y") %> au <%= booking.end_date.strftime("%A %d %B, %Y") %></p>
                <div class="button-booking">
                  <% if policy(booking).edit? %>
                    <p><%= link_to '<i class="fas fa-edit"></i> Éditer'.html_safe, edit_poilu_booking_path(booking.poilu, booking), class: 'link'  %></p>
                  <% end %>
                  <% if policy(booking).destroy? %>
                    <p><%= link_to '<i class="fas fa-trash-alt"></i> Supprimer'.html_safe, poilu_booking_path(booking.poilu, booking), method: :delete, data: { confirm: "Are you sure?" }, class: 'link'  %> </p>
                  <% end %>
                </div>
            </div>
              <% end %>
            <% else %>
              <p>Pas de réservations</p>
            <% end %>
          </div>



        </div>
      </div>
    </div>
  </div>
</div>